name: scrolling_years_calendar_example
description: Demonstrates how to use the scrolling_years_calendar plugin.

environment:
  sdk: '>=2.17.0 <3.0.0'
  # flutter: ^1.5.0

dependencies:
  flutter:
    sdk: flutter
  scrolling_years_calendar:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
