name: scrolling_years_calendar
description: A calendar widget to easily scroll through the years, allowing for customizations to fit your design.
version: 1.3.1
homepage: https://github.com/mennorenkens/flutter_scrolling_calendar

environment:
  sdk: '>=2.07.0 <3.0.0'
  # flutter: ^1.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
